### ISSUE TITLE
Login Api

### ISSUE THREAD

**Issue by CoolVoltage** [CoolVoltage/SnowFlake#1]
1) isUserLoggedIn() - takes no parameters, just check from sesion
2) loginUser(username, password)  - validates, sets session, blah blah blah, returns if login was successful

**Comment by CoolVoltage** [comment]
loginUser is POST and will return success or failure
isUserLoggenIn is GET and will return username or failure
Check code for reply JSON structure

**Comment by ssundarraj** [comment]
Also need an API to log the user out.
